[project]
name = "fred-mcp-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.11.3",
    "fredapi>=0.5.2",
    "openai>=1.99.9",
    "polars>=1.32.3",
]
